### PR TITLE
Adding additional_options parameter to enable custom flags.

### PR DESCRIPTION
**Pull request by acskurucz**

### CODE REVIEW

**Comment by fake-name** [comment]
Oooh, this could be handy!

Thanks!

**Comment by fake-name** [comment]
FYI, this should now be up on PyPi (https://pypi.org/project/ChromeController/). 

0.3.12

**Comment by acskurucz** [comment]
Awesome, thanks!

**Comment by fake-name** [comment]
I'm super happy someone's actually using my stuff. Let me know if you have any questions!

**Pull request merged**
